apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXbHphSGRoY21GdU9rUnZZMnRsY2tBeU1EQXciCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
